### ISSUE TITLE
Can you add ADA as currency?

### ISSUE THREAD

**Issue by QuixoteSystems** [sargatxet/WooCommerce-sargapay#5]
Congrats for your work. This plugin is working perfect! But I suggest, if you let me, that it would be great if you add ADA as currency in the same way you have USD and EUR, because in case you have your website just in ADA (I have several webs) now you can't use this plugin.

If I can help you, let me know. ;-)

**Comment by sargatxet** [comment]
Working on it! Great idea. Thanks.

Missatge de Quixote ***@***.***> del dia dt., 17 de gen. 2023
a les 18:38:

**Comment by QuixoteSystems** [comment]
Perfect! Thanks a lot!

**Comment by Traka-Dev** [comment]
Hi, we have a pre release where we added that feature, you can check it out [here](https://github.com/sargatxet/WooCommerce-sargapay/releases/tag/v2.1.0) I'm working on a translation issues before we launch it to wordpress.org

**Comment by Traka-Dev** [comment]
I finally fixed the translation issues now it works you can check the lates release [here](https://github.com/sargatxet/WooCommerce-sargapay/releases/tag/v2.1.0)  or wait a few hours to be available on [wordpress.org](https://wordpress.org/plugins/sargapay/)

**Comment by QuixoteSystems** [comment]
I just try and all works well but when I'm going to the do the payment Sargapay takes value 0 ADA for Total ADA. I think is getting wrong exchange to ADA because is taking conversion value 0, instead 1.

Maybe I'm wrong but you can see my example here:

![sargapay](https://user-images.githubusercontent.com/82296005/213401757-55bff86e-ae99-4759-8535-2d21692065c4.jpg)

Let me know if I have to change something or I can do more test. FYI right now with I have other payment system (Spoddano) working well all with ADA.

**Comment by Traka-Dev** [comment]
What currency do you have in WooCommerce when the total is 0?

**Comment by QuixoteSystems** [comment]
I just have ADA, so I don't need any currency exchange, the ratio has to be 1:1, I guess.

**Comment by Traka-Dev** [comment]
@QuixoteSystems thanks for reporting this issue, we fixed it should be ok now you can get the latest version [here](https://github.com/sargatxet/WooCommerce-sargapay/releases/tag/v2.1.1) or from [wordpress.org](https://wordpress.org/plugins/sargapay/)

**Comment by QuixoteSystems** [comment]
Yeah I did a test and with this new version works perfect with ADA!! Thanks a lot for your work!!
